# Generated by Django 4.0.4 on 2023-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_ad', models.TextField(default='')),
                ('side_ad', models.TextField(default='')),
                ('simple_content_ad', models.TextField(default='')),
                ('footer_ad', models.TextField(default='')),
                ('fixed_ad', models.TextField(default='')),
                ('show_fixed_ad', models.BooleanField(default=False, verbose_name='show fixed ad')),
            ],
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('white_text_logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('email', models.CharField(default='', max_length=160)),
                ('facebook', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('site_name', models.CharField(default='', max_length=160)),
                ('site_url', models.CharField(default='', max_length=160)),
                ('made_by', models.CharField(default='', max_length=160)),
                ('copyright', models.CharField(default='', max_length=160)),
                ('custome_css', models.TextField(blank=True, default='', null=True)),
                ('head_script', models.TextField(blank=True, default='', null=True)),
                ('bodyend_script', models.TextField(blank=True, default='', null=True)),
                ('show_ads', models.BooleanField(default=False, verbose_name='show all ad')),
            ],
        ),
        migrations.CreateModel(
            name='StaticPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('meta_desc', models.CharField(max_length=160)),
                ('meta_key', models.CharField(max_length=260)),
                ('page_name', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
