# Generated by Django 4.2.5 on 2023-11-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_svgicons_large_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=260)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='svgicons',
            name='faqs_content',
            field=models.ManyToManyField(blank=True, to='home.faqs'),
        ),
    ]
