# Generated by Django 4.2.5 on 2024-01-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faqs_svgicons_faqs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='meta_desc',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='meta_key',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='title',
            field=models.CharField(default='', max_length=160),
        ),
    ]
