# Generated by Django 4.2.5 on 2024-02-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homegroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegroups',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
    ]
