# Generated by Django 4.2.5 on 2024-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homegroups_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegroups',
            name='slug',
            field=models.CharField(default='', max_length=70, unique=False),
        ),
    ]
