# Generated by Django 4.2.5 on 2024-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_svgicons_related_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='group_heading',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='search_heading',
            field=models.CharField(default='', max_length=160),
        ),
    ]
