# Generated by Django 4.2.5 on 2024-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_sitedata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_box_image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
