# Generated by Django 4.2.5 on 2024-05-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_sitedata_home_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='search_heading',
            new_name='home_banner_heading',
        ),
    ]
