# Generated by Django 4.2.5 on 2024-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_search_heading_sitedata_home_banner_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_box_image', models.ImageField(blank=True, null=True, upload_to='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_box_image', models.ImageField(blank=True, null=True, upload_to='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductShowImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_box_image', models.ImageField(blank=True, null=True, upload_to='Product')),
            ],
        ),
        migrations.RenameField(
            model_name='svgicons',
            old_name='content',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='svgicons',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='svgicons',
            name='large_content',
        ),
        migrations.RemoveField(
            model_name='svgicons',
            name='svg_code',
        ),
        migrations.AddField(
            model_name='svgicons',
            name='brand',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='svgicons',
            name='feature',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='svgicons',
            name='model',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='svgicons',
            name='waterproof',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='svgicons',
            name='weight',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='svgicons',
            name='product_images',
            field=models.ManyToManyField(blank=True, to='home.productimages'),
        ),
        migrations.AddField(
            model_name='svgicons',
            name='product_show_images',
            field=models.ManyToManyField(blank=True, to='home.productshowimages'),
        ),
    ]
