# Generated by Django 4.2.5 on 2024-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_svgicons_product_show_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgicons',
            name='price',
            field=models.CharField(default='', max_length=160),
        ),
    ]
