# Generated by Django 4.2.5 on 2024-05-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_svgicons_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimages',
            old_name='category_box_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='category_box_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productshowimages',
            old_name='category_box_image',
            new_name='image',
        ),
    ]
