# Generated by Django 4.2.5 on 2024-05-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_category_box_image_bannerimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='contact_banner',
            field=models.ImageField(blank=True, null=True, upload_to='Contact'),
        ),
    ]
