# Generated by Django 4.2.5 on 2024-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_sitedata_contact_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='address',
            field=models.CharField(default='', max_length=260),
        ),
    ]
