# Generated by Django 4.2.5 on 2024-05-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_sitedata_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('paragraph', models.CharField(max_length=260)),
                ('image', models.ImageField(blank=True, null=True, upload_to='WhatGain')),
            ],
        ),
    ]
