# Generated by Django 4.2.5 on 2024-05-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_whatwedo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgicons',
            name='faqs_content',
        ),
    ]
