# Generated by Django 4.2.5 on 2024-05-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_svgicons_faqs_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SvgIcons',
            new_name='Product',
        ),
    ]
