# Generated by Django 4.2.5 on 2024-05-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_svgicons_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='home_banner_heading',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='home_banner',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='home_banner',
            field=models.ManyToManyField(blank=True, to='home.bannerimages'),
        ),
    ]
