# Generated by Django 4.2.5 on 2024-05-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_sitedata_home_banner_heading_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerImages',
            new_name='HomeBannerImages',
        ),
        migrations.RenameField(
            model_name='sitedata',
            old_name='contact_banner',
            new_name='sidebar_contact_banner',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='home_banner',
        ),
    ]
