# Generated by Django 4.2.5 on 2024-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_bannerimages_homebannerimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='whatsapp_link',
            field=models.CharField(default='', max_length=160),
        ),
    ]
