# Generated by Django 4.2.5 on 2024-05-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_sitedata_group_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='fixed_ad',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='show_fixed_ad',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='side_ad',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='simple_content_ad',
        ),
    ]
