# Generated by Django 4.2.5 on 2024-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_ads_fixed_ad_remove_ads_show_fixed_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='home_about_heading',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='home_about_paragrph',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='home_about_video_link',
            field=models.CharField(default='', max_length=260),
        ),
    ]
