# Generated by Django 4.2.5 on 2024-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_sitedata_home_about_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=260)),
                ('paragrph', models.TextField(default='')),
                ('video_link', models.CharField(default='', max_length=260)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='home_about_heading',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='home_about_paragrph',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='home_about_video_link',
        ),
    ]
