# Generated by Django 4.2.5 on 2024-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_homeaboutsection_remove_sitedata_home_about_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeaboutsection',
            name='video_link',
        ),
        migrations.AddField(
            model_name='homeaboutsection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
