# Generated by Django 4.2.5 on 2024-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_homeaboutsection_video_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='whatwedo')),
                ('heading', models.CharField(default='', max_length=260)),
                ('paragrph', models.TextField(default='')),
            ],
        ),
    ]
