# Generated by Django 4.2.5 on 2024-07-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_whatwedobox'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Contact Us', max_length=260, null=True)),
                ('paragraph', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='HomePartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_partner_images')),
                ('home_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.homepartners')),
            ],
        ),
    ]
