# Generated by Django 4.2.5 on 2024-07-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_homepartners_homepartnerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepartners',
            name='BackgroundImg',
            field=models.ImageField(blank=True, null=True, upload_to='partners'),
        ),
    ]
