# Generated by Django 4.2.5 on 2024-07-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_homepartners_backgroundimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('meta_desc', models.CharField(max_length=160)),
                ('meta_key', models.CharField(max_length=260)),
                ('page_name', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
