# Generated by Django 4.2.5 on 2024-07-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_newsposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsposts',
            name='page_name',
        ),
        migrations.AddField(
            model_name='newsposts',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
