# Generated by Django 4.2.5 on 2024-07-31 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_newsposts_page_name_newsposts_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
