# Generated by Django 4.2.5 on 2024-07-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_newsposts_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='faqs',
            name='heading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='home.faqheading'),
        ),
    ]
