# Generated by Django 4.2.5 on 2024-07-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_faqheading_faqs_heading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaqHeading',
            new_name='AddFaq',
        ),
    ]
