# Generated by Django 4.2.5 on 2024-07-31 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_rename_faqheading_addfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='OemOdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(null=True, upload_to='oemodm')),
                ('heading', models.CharField(max_length=160)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='oemodm')),
                ('heading', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oemodm', to='home.oemodm')),
            ],
        ),
    ]
