# Generated by Django 4.2.5 on 2024-07-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_oemodm_oem'),
    ]

    operations = [
        migrations.AddField(
            model_name='oem',
            name='main_heading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oemodm', to='home.oemodm'),
        ),
        migrations.AlterField(
            model_name='oem',
            name='heading',
            field=models.CharField(max_length=260),
        ),
    ]
