# Generated by Django 4.2.5 on 2024-08-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_oemcustom_oemcustombox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='show_ads',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='show all ad',
            field=models.BooleanField(default=False, verbose_name='show_ads'),
        ),
        migrations.AlterField(
            model_name='addfaq',
            name='heading',
            field=models.CharField(max_length=160, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='footer_ad',
            field=models.TextField(default='', verbose_name='footer_ad'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='head_ad',
            field=models.TextField(default='', verbose_name='head_ad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='category_banner_img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_box_image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='category_box_image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=160, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(upload_to='Certificate', verbose_name='certificate_image'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.CharField(max_length=260, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='heading',
            field=models.CharField(default='', max_length=260, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='paragrph',
            field=models.TextField(default='', verbose_name='paragrph'),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video_file'),
        ),
        migrations.AlterField(
            model_name='homebannerimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='homegroups',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='homegroups',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=260, null=True, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='homegroups',
            name='slug',
            field=models.CharField(default='', max_length=70, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='homepartnerimage',
            name='image',
            field=models.ImageField(upload_to='home_partner_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='homepartners',
            name='BackgroundImg',
            field=models.ImageField(blank=True, null=True, upload_to='partners', verbose_name='BackgroundImg'),
        ),
        migrations.AlterField(
            model_name='homepartners',
            name='heading',
            field=models.CharField(blank=True, default='Contact Us', max_length=260, null=True, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='homepartners',
            name='paragraph',
            field=models.TextField(default='', verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='news', verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='meta_desc',
            field=models.CharField(max_length=160, verbose_name='meta_desc'),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='meta_key',
            field=models.CharField(max_length=260, verbose_name='meta_key'),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='slug',
            field=models.CharField(max_length=70, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='title',
            field=models.CharField(max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='oem',
            name='heading',
            field=models.CharField(max_length=260, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='oem',
            name='image',
            field=models.ImageField(null=True, upload_to='oemodm', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='oem',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='oemcustom',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='oemodm', verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='oemcustom',
            name='heading',
            field=models.CharField(max_length=160, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='oemcustombox',
            name='heading',
            field=models.CharField(max_length=260, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='oemcustombox',
            name='image',
            field=models.ImageField(null=True, upload_to='oemodm', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='oemcustombox',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='oemodm',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='oemodm', verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='oemodm',
            name='heading',
            field=models.CharField(max_length=160, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='oemodm',
            name='paragraph',
            field=models.TextField(verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=160, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(default='', max_length=160, verbose_name='feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_desc',
            field=models.CharField(max_length=160, verbose_name='meta_desc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_key',
            field=models.CharField(max_length=260, verbose_name='meta_key'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='', max_length=160, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='', max_length=160, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(to='home.productimages', verbose_name='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_show_images',
            field=models.ManyToManyField(to='home.productshowimages', verbose_name='product_show_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=70, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waterproof',
            field=models.CharField(default='', max_length=160, verbose_name='waterproof'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default='', max_length=160, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Product', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productshowimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Product', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='address',
            field=models.CharField(default='', max_length=260, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='author',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='bodyend_script',
            field=models.TextField(blank=True, default='', null=True, verbose_name='bodyend_script'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='copyright',
            field=models.CharField(default='', max_length=160, verbose_name='copyright'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='custome_css',
            field=models.TextField(blank=True, default='', null=True, verbose_name='custome_css'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='email',
            field=models.CharField(default='', max_length=160, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='fav_icon',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='fav_icon'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='head_script',
            field=models.TextField(blank=True, default='', null=True, verbose_name='head_script'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='made_by',
            field=models.CharField(default='', max_length=160, verbose_name='made_by'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='meta_desc',
            field=models.CharField(default='', max_length=160, verbose_name='meta_desc'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='meta_key',
            field=models.CharField(default='', max_length=260, verbose_name='meta_key'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='phone',
            field=models.CharField(default='', max_length=160, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='search_desc',
            field=models.CharField(default='', max_length=160, verbose_name='search_desc'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='search_key',
            field=models.CharField(default='', max_length=160, verbose_name='search_key'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='sidebar_contact_banner',
            field=models.ImageField(blank=True, null=True, upload_to='Contact', verbose_name='sidebar_contact_banner'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='site_name',
            field=models.CharField(default='', max_length=160, verbose_name='site_name'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='site_url',
            field=models.CharField(default='', max_length=160, verbose_name='site_url'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='title',
            field=models.CharField(default='', max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='whatsapp_link',
            field=models.CharField(default='', max_length=160, verbose_name='whatsapp_link'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='white_text_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='white_text_logo'),
        ),
        migrations.AlterField(
            model_name='staticposts',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='staticposts',
            name='meta_desc',
            field=models.CharField(max_length=160, verbose_name='meta_desc'),
        ),
        migrations.AlterField(
            model_name='staticposts',
            name='meta_key',
            field=models.CharField(max_length=260, verbose_name='meta_key'),
        ),
        migrations.AlterField(
            model_name='staticposts',
            name='page_name',
            field=models.CharField(max_length=70, verbose_name='page_name'),
        ),
        migrations.AlterField(
            model_name='staticposts',
            name='slug',
            field=models.CharField(max_length=70, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='staticposts',
            name='title',
            field=models.CharField(max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='whatgain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WhatGain', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='whatgain',
            name='paragraph',
            field=models.CharField(max_length=260, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='whatgain',
            name='title',
            field=models.CharField(max_length=160, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='banner_image',
            field=models.ImageField(upload_to='WhatWeDo', verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='paragraph',
            field=models.CharField(max_length=260, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='title',
            field=models.CharField(max_length=160, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='whatwedobox',
            name='heading',
            field=models.CharField(default='', max_length=260, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='whatwedobox',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='whatwedo', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='whatwedobox',
            name='paragrph',
            field=models.TextField(default='', verbose_name='paragrph'),
        ),
    ]
