# Generated by Django 4.2.5 on 2024-08-03 12:18

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_remove_sitedata_show_ads_sitedata_show_all_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfaq',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='question',
        ),
        migrations.RemoveField(
            model_name='homeaboutsection',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homeaboutsection',
            name='paragrph',
        ),
        migrations.RemoveField(
            model_name='homegroups',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homepartners',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homepartners',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='newsposts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newsposts',
            name='meta_desc',
        ),
        migrations.RemoveField(
            model_name='newsposts',
            name='meta_key',
        ),
        migrations.RemoveField(
            model_name='newsposts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='oem',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='oem',
            name='text',
        ),
        migrations.RemoveField(
            model_name='oemcustom',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='oemcustombox',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='oemcustombox',
            name='text',
        ),
        migrations.RemoveField(
            model_name='oemodm',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='oemodm',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_key',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_show_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='waterproof',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='bodyend_script',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='copyright',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='custome_css',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='head_script',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='meta_desc',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='meta_key',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='search_desc',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='search_key',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='show all ad',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='staticposts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='staticposts',
            name='meta_desc',
        ),
        migrations.RemoveField(
            model_name='staticposts',
            name='meta_key',
        ),
        migrations.RemoveField(
            model_name='staticposts',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='staticposts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='whatgain',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='whatgain',
            name='title',
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='whatwedobox',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='whatwedobox',
            name='paragrph',
        ),
        migrations.CreateModel(
            name='WhatWeDoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name='title')),
                ('paragraph', models.CharField(max_length=260, verbose_name='paragraph')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.whatwedo')),
            ],
            options={
                'verbose_name': 'what we do Translation',
                'db_table': 'home_whatwedo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='WhatWeDoBoxTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(default='', max_length=260, verbose_name='heading')),
                ('paragrph', models.TextField(default='', verbose_name='paragrph')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.whatwedobox')),
            ],
            options={
                'verbose_name': 'what we do box Translation',
                'db_table': 'home_whatwedobox_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='WhatGainTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name='title')),
                ('paragraph', models.CharField(max_length=260, verbose_name='paragraph')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.whatgain')),
            ],
            options={
                'verbose_name': 'what gain Translation',
                'db_table': 'home_whatgain_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='StaticPostsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('meta_desc', models.CharField(max_length=160, verbose_name='meta_desc')),
                ('meta_key', models.CharField(max_length=260, verbose_name='meta_key')),
                ('page_name', models.CharField(max_length=70, verbose_name='page_name')),
                ('content', models.TextField(verbose_name='content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.staticposts')),
            ],
            options={
                'verbose_name': 'static posts Translation',
                'db_table': 'home_staticposts_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='SiteDataTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(default='', max_length=160, verbose_name='title')),
                ('meta_desc', models.CharField(default='', max_length=160, verbose_name='meta_desc')),
                ('meta_key', models.CharField(default='', max_length=260, verbose_name='meta_key')),
                ('email', models.CharField(default='', max_length=160, verbose_name='email')),
                ('phone', models.CharField(default='', max_length=160, verbose_name='phone')),
                ('whatsapp_link', models.CharField(default='', max_length=160, verbose_name='whatsapp_link')),
                ('address', models.CharField(default='', max_length=260, verbose_name='address')),
                ('facebook', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='facebook')),
                ('instagram', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='instagram')),
                ('twitter', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='twitter')),
                ('author', models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='author')),
                ('site_name', models.CharField(default='', max_length=160, verbose_name='site_name')),
                ('site_url', models.CharField(default='', max_length=160, verbose_name='site_url')),
                ('made_by', models.CharField(default='', max_length=160, verbose_name='made_by')),
                ('copyright', models.CharField(default='', max_length=160, verbose_name='copyright')),
                ('search_key', models.CharField(default='', max_length=160, verbose_name='search_key')),
                ('search_desc', models.CharField(default='', max_length=160, verbose_name='search_desc')),
                ('custome_css', models.TextField(blank=True, default='', null=True, verbose_name='custome_css')),
                ('head_script', models.TextField(blank=True, default='', null=True, verbose_name='head_script')),
                ('bodyend_script', models.TextField(blank=True, default='', null=True, verbose_name='bodyend_script')),
                ('show all ad', models.BooleanField(default=False, verbose_name='show_ads')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.sitedata')),
            ],
            options={
                'verbose_name': 'site data Translation',
                'db_table': 'home_sitedata_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('meta_desc', models.CharField(max_length=160, verbose_name='meta_desc')),
                ('meta_key', models.CharField(max_length=260, verbose_name='meta_key')),
                ('brand', models.CharField(default='', max_length=160, verbose_name='brand')),
                ('model', models.CharField(default='', max_length=160, verbose_name='model')),
                ('weight', models.CharField(default='', max_length=160, verbose_name='weight')),
                ('waterproof', models.CharField(default='', max_length=160, verbose_name='waterproof')),
                ('feature', models.CharField(default='', max_length=160, verbose_name='feature')),
                ('details', models.TextField(verbose_name='details')),
                ('price', models.CharField(default='', max_length=160, verbose_name='price')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.product')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'home_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='OemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(max_length=260, verbose_name='heading')),
                ('text', models.TextField(verbose_name='text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.oem')),
            ],
            options={
                'verbose_name': 'oem Translation',
                'db_table': 'home_oem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='OemOdmTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(max_length=160, verbose_name='heading')),
                ('paragraph', models.TextField(verbose_name='paragraph')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.oemodm')),
            ],
            options={
                'verbose_name': 'oem odm Translation',
                'db_table': 'home_oemodm_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='OemCustomTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(max_length=160, verbose_name='heading')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.oemcustom')),
            ],
            options={
                'verbose_name': 'oem custom Translation',
                'db_table': 'home_oemcustom_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='OemCustomBoxTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(max_length=260, verbose_name='heading')),
                ('text', models.TextField(verbose_name='text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.oemcustombox')),
            ],
            options={
                'verbose_name': 'oem custom box Translation',
                'db_table': 'home_oemcustombox_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='NewsPostsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('meta_desc', models.CharField(max_length=160, verbose_name='meta_desc')),
                ('meta_key', models.CharField(max_length=260, verbose_name='meta_key')),
                ('content', models.TextField(verbose_name='content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.newsposts')),
            ],
            options={
                'verbose_name': 'news posts Translation',
                'db_table': 'home_newsposts_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='HomePartnersTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(blank=True, default='Contact Us', max_length=260, null=True, verbose_name='heading')),
                ('paragraph', models.TextField(default='', verbose_name='paragraph')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homepartners')),
            ],
            options={
                'verbose_name': 'home partners Translation',
                'db_table': 'home_homepartners_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='HomeGroupsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(blank=True, default='', max_length=260, null=True, verbose_name='heading')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homegroups')),
            ],
            options={
                'verbose_name': 'home groups Translation',
                'db_table': 'home_homegroups_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='HomeAboutSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(default='', max_length=260, verbose_name='heading')),
                ('paragrph', models.TextField(default='', verbose_name='paragrph')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homeaboutsection')),
            ],
            options={
                'verbose_name': 'home about section Translation',
                'db_table': 'home_homeaboutsection_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='FaqsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=260, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.faqs')),
            ],
            options={
                'verbose_name': 'faqs Translation',
                'db_table': 'home_faqs_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'home_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='AddFaqTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(max_length=160, verbose_name='heading')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.addfaq')),
            ],
            options={
                'verbose_name': 'add faq Translation',
                'db_table': 'home_addfaq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
