# Generated by Django 4.2.5 on 2024-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_rename_facebook_sitedata_alibaba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('link', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='SocialIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_icon_code', models.TextField()),
                ('icon_name', models.CharField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='sitedata',
            name='menu_list',
            field=models.ManyToManyField(blank=True, to='home.navmenu'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='social_icons',
            field=models.ManyToManyField(blank=True, to='home.socialicons'),
        ),
    ]
