# Generated by Django 4.2.5 on 2024-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_remove_addfaq_heading_remove_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_banner_img',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_box_image',
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='category_banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='category_banner_img'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='category_box_image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='category_box_image'),
        ),
    ]
