# Generated by Django 4.2.5 on 2024-08-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_rename_icon_name_socialicons_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialicons',
            name='name',
            field=models.CharField(default='', max_length=160),
        ),
    ]
