# Generated by Django 4.2.5 on 2024-08-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_socialicons_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='social_icons',
            new_name='social_links',
        ),
    ]
