# Generated by Django 4.2.5 on 2024-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_rename_social_icons_sitedata_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='nav_products_list',
            field=models.ManyToManyField(blank=True, to='home.product'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='nav_products_section_heading',
            field=models.CharField(default='', max_length=260),
        ),
    ]
