# Generated by Django 4.2.5 on 2024-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_sitedata_nav_products_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='nav_products_list',
            field=models.ManyToManyField(blank=True, to='home.category'),
        ),
    ]
