# Generated by Django 4.2.5 on 2024-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_remove_product_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='all_product_page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='contact_page_bg',
            field=models.ImageField(blank=True, null=True, upload_to='Contact'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='whatsapp_qr_img',
            field=models.ImageField(blank=True, null=True, upload_to='Contact'),
        ),
    ]
