# Generated by Django 4.2.5 on 2024-08-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_sitedata_all_product_page_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=160)),
                ('meta_desc', models.CharField(default='', max_length=160)),
                ('meta_key', models.CharField(default='', max_length=260)),
                ('about_page_heading', models.CharField(default='', max_length=160)),
                ('about_page_paragraph', models.CharField(default='', max_length=160)),
                ('star_banner_image', models.ImageField(upload_to='about_page')),
                ('customer_heading', models.CharField(default='', max_length=160)),
                ('oem_odm_heading', models.CharField(default='', max_length=160)),
                ('our_story_heading', models.CharField(default='', max_length=160)),
                ('our_story_content', models.TextField(default='')),
                ('end_banner_image', models.ImageField(upload_to='about_page')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_page')),
                ('heading', models.CharField(default='', max_length=160)),
                ('text', models.TextField(default='')),
                ('customer_boxe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_box', to='home.aboutpage')),
            ],
        ),
    ]
