# Generated by Django 4.2.5 on 2024-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_rename_customer_boxe_customerbox_customer_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='star_banner_image',
            new_name='start_banner_image',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_page_paragraph',
            field=models.TextField(default=''),
        ),
    ]
