# Generated by Django 4.2.5 on 2024-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_homeaboutsection_heading_homeaboutsection_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaboutsection',
            name='heading',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='label',
            field=models.CharField(default='', max_length=260),
        ),
    ]
