# Generated by Django 4.2.5 on 2024-12-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alter_homeaboutsection_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=160)),
                ('banner_image', models.ImageField(null=True, upload_to='faqs')),
            ],
        ),
    ]
