# Generated by Django 4.2.5 on 2024-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_faqbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(default='', max_length=160)),
                ('product_heading', models.CharField(default='', max_length=160)),
                ('contact_heading', models.CharField(default='', max_length=160)),
            ],
        ),
    ]
