# Generated by Django 4.2.5 on 2024-12-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_footerheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatGainHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=160)),
                ('label', models.CharField(default='', max_length=160)),
            ],
        ),
    ]
