# Generated by Django 4.2.5 on 2024-12-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_whatgainheading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatgainheading',
            old_name='label',
            new_name='paragraph',
        ),
    ]
