# Generated by Django 4.2.5 on 2024-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=160),
        ),
    ]
