# Generated by Django 4.2.5 on 2024-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_sitedata_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebannerimages',
            name='link',
            field=models.CharField(default='', max_length=360),
        ),
    ]
